baseURL = 'https://aicodingplaybook.ru/'
canonifyURLs = true
relativeURLs = false
languageCode = 'ru'
title = 'AI Coding Playbook'
theme = 'ananke'
copyright = 'AI Coding Playbook'

[pagination]
pagerSize = 10000

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 2
startLevel = 2

[params]
recent_posts_number = 10000
background_color_class = 'bg-book'
body_classes = 'avenir bg-book'
custom_css = ['css/custom.css']
favicon = '/favicon.ico'

[params.banner]
enabled = false

[[menu.main]]
name = 'Связаться'
url = 'https://aihubteam.ru/'
weight = 100
