baseURL = 'https://aicodingplaybook.ru/'
canonifyURLs = true
relativeURLs = false
languageCode = 'ru'
title = 'AI Coding Playbook'
theme = 'ananke'
copyright = 'AI HUB TEAM'

[outputs]
home = ['HTML', 'RSS', 'JSON']

[pagination]
pagerSize = 10000

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 2
startLevel = 2

[params]
recent_posts_number = 10000
background_color_class = 'bg-book'
body_classes = 'avenir bg-book'
custom_css = ['css/custom.css']
favicon = '/favicon.ico'
description = 'Практическое руководство по внедрению ИИ-инструментов для кодинга в компанию'
images = ['images/print_machine.png']

[params.banner]
enabled = false

[[menu.main]]
name = 'Changelog'
url = '/changelog/'
weight = 80

[[menu.main]]
name = 'О проекте'
url = '/about/'
weight = 90

[[menu.main]]
name = 'Связаться'
url = 'https://t.me/crazyfrogspb'
weight = 100
